fix(costmodels): add input validation to description, name and tags
project-koku/koku-ui pull request #1767
Opened 2020-12-03 10:33 UTC by boaz0

closes COST 781

The following verification were added to fields like `cost model name`, `cost model description`, `tag key`, `tag values` and `tag description`:
1) Making sure that the input is not exceeding a certain length.
2) Making sure that the input includes only valid characters

2020-12-04 03:19 UTC, dlabrecq approved these changes

2020-12-06 21:51 UTC, boaz0 commented
Did some updates:
1) change the limit to what is set in [here](https://github.com/project-koku/koku/pull/2541)
2) remove the regexp because this is not necessary. According to [React docs](https://reactjs.org/docs/jsx-in-depth.html):

> When you pass a string literal, its value is HTML-unescaped. So these two JSX expressions are equivalent:
```
<MyComponent message="&lt;3" />
<MyComponent message={'<3'} />
```

However, if we set `dangerouslySetInnerHTML` in the JSX then this is no longer valid.

2020-12-06 22:20 UTC, dlabrecq requested changes
Linter failed

2020-12-07 14:32 UTC, dlabrecq approved these changes

2020-12-07 14:33 UTC, merged