[COST-3554] Use new field for amortized cost
project-koku/koku-ui pull request #3173
Opened 2023-05-10 21:26 UTC by samdoran

The value in `savingsplan_effective_cost` does not accurately reflect the amortized cost as reported by AWS. There is a new field that calculates the correct amortized cost the same way that AWS does. Use this new field when amortized cost is selected.

2023-05-10 21:28 UTC, samdoran commented
Turns out there was a minor UI change needed after all. Sorry for any confusion. I don't think this should be a huge change (famous last words).

2023-05-11 02:36 UTC, dlabrecq requested changes
Is the API change available in stage?

Multiple API requests error with "400 Bad Request".

{"cost_type":["\"calculated_amortized_cost\" is not a valid choice."]}

**API request example**
`api/cost-management/v1/reports/aws/costs/?cost_type=calculated_amortized_cost&currency=USD&filter[resolution]=daily&filter[time_scope_units]=month&filter[time_scope_value]=-2`

**Browser inspector**
![Screenshot 2023-05-10 at 10 33 26 PM](https://github.com/project-koku/koku-ui/assets/17481322/9aeb065e-9720-429e-b9b5-6ff83858babd)

2023-05-11 02:40 UTC, dlabrecq commented
@samdoran Why does the API support both `calculated_amortized_cost` and `savingsplan_effective_cost`?

Why not just fix the existing `savingsplan_effective_cost` param if that's not accurate?

2023-05-11 14:20 UTC, samdoran commented
API changes haven't been merged yet. https://github.com/project-koku/koku/pull/4365

I'll switch this to a draft until after that is merged.

2023-05-11 14:25 UTC, samdoran commented
> Why does the API support both calculated_amortized_cost and savingsplan_effective_cost?

That's for backwards compatibility for anyone using the API directly and requesting `savingsplan_effective_cost`.

> Why not just fix the existing savingsplan_effective_cost param if that's not accurate?

That value comes directly from AWS. They don't provide a value in the cost report data for amortized cost that matches how they calculate it, so we have to calculate it ourselves based on existing data and store that. We could overwrite `savingsplan_effective_cost` but that may confuse someone who notices the value from the cost report is different than what our app reports.

2023-06-14 17:25 UTC, samdoran commented
Turns out I was wrong about where this setting is used: this doesn't change the value stored in settings but rather the value used in the Show cost as drop down menu.

https://github.com/project-koku/koku/pull/4365 is deployed to stage. We can merge this in order to test it in stage.

This needs to be merged to prod _after_ https://github.com/project-koku/koku/pull/4365 is deployed to prod.

2023-06-15 01:03 UTC, dlabrecq approved these changes
Tested UI locally and LGTM

2023-06-15 01:03 UTC, merged

2023-06-15 02:01 UTC, samdoran commented
Thank you!